/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JViewport;

/**
 *
 * @author deadlock
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        jScrollPane1.setViewportView(new AssocTarefas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setPreferredSize(new java.awt.Dimension(900, 720));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Problema de Associação de Tarefas (Assignment Problem)", "Codificação de Huffman para compressão de um texto fornecido pelo usuário", "Problema da Mochila Fracionária (Fractional Knapsack Problem)", "Problema da Mochila Booleana (mochila 0-1 – em inglês, Knapsack Problem)", "Problema da Subsequência Comum Máxima (Longest Common Subsequence)", "Problema da Multiplicação de Cadeia de Matrizes (Matrix Chain Multiplication)" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, 586, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        switch((String)jComboBox1.getSelectedItem()){
            case "Problema da Mochila Fracionária (Fractional Knapsack Problem)":
                    jScrollPane1.setViewportView(new MochilaFracionaria());
            break;
            
            case "Problema da Multiplicação de Cadeia de Matrizes (Matrix Chain Multiplication)":
                jScrollPane1.setViewportView(new MultMatriz());
            break;
            
            case "Problema de Associação de Tarefas (Assignment Problem)":
                jScrollPane1.setViewportView(new AssocTarefas());
            break;
            
            case "Problema da Mochila Booleana (mochila 0-1 – em inglês, Knapsack Problem)":
                 jScrollPane1.setViewportView(new MochilaBooleanaGui());
            break;
            
            case "Problema da Subsequência Comum Máxima (Longest Common Subsequence)":
                jScrollPane1.setViewportView(new Subseq());
            break;
            
            case "Codificação de Huffman para compressão de um texto fornecido pelo usuário":
                jScrollPane1.setViewportView(new HuffmanGui());
            break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
